"""Iterative SFT iter-1 generator for intercode (LEAP-style).

Recipe (paper: "Better than Your Teacher", arXiv 2410.05434, intercode-bash
60.3% -> 71.8%):

    iter0:  SFT on the whitelisted dataset's gold (instruction, response).
              <-- our existing pipeline: intercode_trajectories + tokenize + train.
    iter1:  1. Use the iter0 model to GENERATE new ReAct trajectories on the
               same task set (real execution inside LocalBashEnv).
            2. Score each trajectory against the gold (stdout similarity).
            3. FILTER: keep only trajectories with reward >= threshold
               (rejection sampling).
            4. SFT iter1 on (filtered trajectories) + optionally a fraction
               of iter0 gold for stability.

Gated by env var INTERCODE_ITER_SFT (default 0). When the flag is flipped, the
orchestrator (text_trainer or a follow-up wrapper) calls run_iter1_phase()
between the iter0 SFT and a second SFT pass.

This module is now IMPLEMENTED (was a scaffold). Inference uses HuggingFace
transformers `generate` directly on the iter0 LoRA-merged model — self-contained,
no separate inference server. That is correct but SLOW (no paged-attention /
batching); cap the work with `max_tasks` to fit the wall-clock budget. The
production upgrade is to swap _build_generator for an sglang/vLLM client (the
rest of the pipeline is server-agnostic). The reward here approximates the eval's
stdout component via token cosine between the agent's final observation and the
gold command's observation — sufficient for rejection sampling on the read-heavy
NL2Bash task set where we plateau.

Every entry point is NEVER-RAISE: any failure (no GPU, model load error, bad
dataset, sandbox damage) logs and returns a fall-back value so the caller drops
to a single-pass SFT. Compute cost roughly doubles the SFT budget, so use only
on the 3.0h FROM_SCRATCH path or offline.

Cheating-review safety: like the rest of zeus's intercode work, iter1
trajectories are generated by REAL execution in the bash sandbox at train
time -- this is "real training", not pre-saved results.
"""

from __future__ import annotations

import json
import math
import os
import re
from collections import Counter
from pathlib import Path


DEFAULT_REWARD_THRESHOLD = 0.5  # keep trajectories with reward >= this
DEFAULT_KEEP_ITER0_FRACTION = 0.25  # advisory: caller may mix this much iter0 gold
DEFAULT_MAX_TASKS = 800  # budget cap (transformers generate is slow); tune per budget
_MAX_NEW_TOKENS = 256
_OBS_TRUNCATE = 350  # match validator DEFAULT_OBS_TRUNCATE_CHARS

_QUERY_KEYS = ("query", "instruction", "nl", "question", "prompt", "input", "intent")
_GOLD_KEYS = ("gold", "cmd", "command", "bash", "gold_cmd", "response", "code", "answer", "output")


def iter_sft_enabled() -> bool:
    """Toggle: INTERCODE_ITER_SFT=1 to run iter1. Default off."""
    return os.environ.get("INTERCODE_ITER_SFT", "0").strip() not in ("0", "false", "no", "")


# ---------------------------------------------------------------------------
# Inference (transformers; swap for sglang/vLLM client for speed)
# ---------------------------------------------------------------------------

def _build_generator(model_path: "str | Path"):
    """Return a generate(prompt:str, temperature:float)->str callable, or None.

    Loads the iter0 LoRA-merged model with transformers. Never raises -- returns
    None on any failure so the caller skips iter1.
    """
    try:
        import torch
        from transformers import AutoModelForCausalLM, AutoTokenizer
    except Exception as exc:  # torch/transformers missing
        print(f"[intercode_iter1_gen] inference deps unavailable: {exc}", flush=True)
        return None
    try:
        tok = AutoTokenizer.from_pretrained(str(model_path))
        model = AutoModelForCausalLM.from_pretrained(
            str(model_path), torch_dtype=torch.float16, device_map="auto"
        )
        model.eval()
    except Exception as exc:
        print(f"[intercode_iter1_gen] model load failed ({model_path}): {exc}", flush=True)
        return None

    pad_id = tok.pad_token_id if tok.pad_token_id is not None else tok.eos_token_id

    def _gen(prompt: str, temperature: float = 0.7) -> str:
        try:
            inputs = tok(prompt, return_tensors="pt", truncation=True, max_length=8192).to(model.device)
            with torch.no_grad():
                out = model.generate(
                    **inputs,
                    do_sample=temperature > 0,
                    temperature=max(float(temperature), 1e-2),
                    top_p=0.95,
                    max_new_tokens=_MAX_NEW_TOKENS,
                    pad_token_id=pad_id,
                )
            new = out[0][inputs["input_ids"].shape[1]:]
            return tok.decode(new, skip_special_tokens=True)
        except Exception as exc:
            print(f"[intercode_iter1_gen] generate failed: {exc}", flush=True)
            return ""

    return _gen


# ---------------------------------------------------------------------------
# ReAct rollout + reward
# ---------------------------------------------------------------------------

def _parse_turn(gen_text: str, turn: int) -> "tuple[str, str] | tuple[None, None]":
    """Split a generated continuation into (assistant_content, action_payload).

    The model continues from "Thought {turn}:" with " {thought}\\nAction {turn}:
    {payload}". Returns the assistant text up to the end of that action line and
    the raw action payload, or (None, None) if no action line is present.
    """
    m = re.search(rf"Action\s*{turn}\s*:\s*(.+)", gen_text)
    if not m:
        return None, None
    action_payload = m.group(1).strip()
    asst = gen_text[: m.end()].rstrip()
    if not asst.startswith(" "):
        asst = " " + asst
    return asst, action_payload


def _react_rollout(gen, query: str, env, max_turns: int, temperature: float):
    """Run the iter0 model through one task in the live sandbox.

    Returns (messages, last_observation, did_submit). `messages` is a chat list
    in the same shape as build_intercode_multiturn_example so the existing
    tokenize/train chain accepts it unchanged.
    """
    from our_envs.intercode_format import REACT_INIT_MSG, DEMO_BASH_REACT, _parse_action

    first_user = REACT_INIT_MSG + DEMO_BASH_REACT + f"Question: {query}\nThought 1:"
    messages = [{"role": "user", "content": first_user}]
    running = first_user
    last_obs = ""
    did_submit = False

    for turn in range(1, max_turns + 1):
        gen_text = gen(running, temperature)
        if not gen_text:
            break
        asst, action_payload = _parse_turn(gen_text, turn)
        if asst is None:
            break
        messages.append({"role": "assistant", "content": asst})

        payload, ok = _parse_action(action_payload)
        if payload == "submit":
            did_submit = True
            break
        if not ok:
            break
        try:
            obs = env.step(payload)
        except Exception as exc:
            print(f"[intercode_iter1_gen] sandbox step failed: {exc}", flush=True)
            break
        obs = (obs or "")[:_OBS_TRUNCATE]
        last_obs = obs
        user_delta = f"Observation {turn}: {obs}\nThought {turn + 1}:"
        messages.append({"role": "user", "content": user_delta})
        running = running + asst + "\n" + user_delta

    return messages, last_obs, did_submit


def _token_cosine(a: str, b: str) -> float:
    """Whitespace-token TF cosine in [0,1]. Approximates the eval's stdout reward."""
    a, b = (a or "").strip(), (b or "").strip()
    if not a and not b:
        return 1.0
    ca, cb = Counter(a.split()), Counter(b.split())
    if not ca or not cb:
        return 1.0 if a == b else 0.0
    common = set(ca) & set(cb)
    dot = sum(ca[t] * cb[t] for t in common)
    na = math.sqrt(sum(v * v for v in ca.values()))
    nb = math.sqrt(sum(v * v for v in cb.values()))
    return dot / (na * nb) if na and nb else 0.0


def _gold_observation(gold: str, fs: int, LBE, snapshot_root) -> "str | None":
    """Run the gold command in a fresh sandbox; return its observation or None."""
    try:
        env = LBE(fs_version=fs, snapshot_root=snapshot_root)
        env.reset()
        return (env.step(gold) or "")[:_OBS_TRUNCATE]
    except Exception as exc:
        print(f"[intercode_iter1_gen] gold exec failed: {exc}", flush=True)
        return None


# ---------------------------------------------------------------------------
# Task loading
# ---------------------------------------------------------------------------

def _extract(row: dict, keys: "tuple[str, ...]") -> str:
    for k in keys:
        v = row.get(k)
        if v:
            return str(v).strip()
    return ""


def _load_tasks(task_dataset_path: "str | Path", max_tasks: "int | None") -> "list[tuple[str, str]]":
    """Load (query, gold) pairs from a HF dataset dir or a JSON/JSONL file. Never raises."""
    path = str(task_dataset_path)
    rows: list[dict] = []
    try:
        if Path(path).is_dir():
            from datasets import load_from_disk
            ds = load_from_disk(path)
            split = ds["train"] if hasattr(ds, "keys") and "train" in ds else ds
            rows = list(split)
        elif path.endswith(".jsonl"):
            with open(path, encoding="utf-8") as f:
                rows = [json.loads(line) for line in f if line.strip()]
        else:
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
            rows = data if isinstance(data, list) else data.get("data", [])
    except Exception as exc:
        print(f"[intercode_iter1_gen] task load failed ({path}): {exc}", flush=True)
        return []

    out: list[tuple[str, str]] = []
    for row in rows:
        if not isinstance(row, dict):
            continue
        q, g = _extract(row, _QUERY_KEYS), _extract(row, _GOLD_KEYS)
        if q and g:
            out.append((q, g))
        if max_tasks and len(out) >= max_tasks:
            break
    return out


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------

def generate_iter1_trajectories(
    model_path: "str | Path",
    task_dataset_path: "str | Path",
    snapshot_root: "str | Path",
    output_path: "str | Path",
    *,
    max_tasks: "int | None" = DEFAULT_MAX_TASKS,
    max_turns: int = 10,
    temperature: float = 0.7,
) -> int:
    """Drive the iter0 model through tasks; write scored ReAct trajectories as JSONL.

    Each line: {"messages": [...], "reward": float}. Returns the count written.
    Never raises -- returns 0 on any setup failure so the caller falls back.
    """
    gen = _build_generator(model_path)
    if gen is None:
        return 0
    try:
        from our_envs.intercode_local_bash_env import (
            LocalBashEnv,
            detect_fs_for_gold,
            is_safe_for_real_exec,
        )
    except Exception as exc:
        print(f"[intercode_iter1_gen] sandbox import failed: {exc}", flush=True)
        return 0

    tasks = _load_tasks(task_dataset_path, max_tasks)
    if not tasks:
        print("[intercode_iter1_gen] no tasks loaded; skipping iter1 gen.", flush=True)
        return 0

    written = 0
    try:
        with open(output_path, "w", encoding="utf-8") as fout:
            for i, (query, gold) in enumerate(tasks):
                try:
                    fs = detect_fs_for_gold(gold)
                    if fs == -1 or not is_safe_for_real_exec(gold):
                        continue
                    env = LocalBashEnv(fs_version=fs, snapshot_root=snapshot_root)
                    env.reset()
                    messages, last_obs, did_submit = _react_rollout(
                        gen, query, env, max_turns, temperature
                    )
                    gold_obs = _gold_observation(gold, fs, LocalBashEnv, snapshot_root)
                    if gold_obs is None:
                        continue
                    reward = _token_cosine(last_obs, gold_obs) if did_submit else 0.0
                    fout.write(json.dumps({"messages": messages, "reward": reward}) + "\n")
                    written += 1
                    if written % 100 == 0:
                        print(f"[intercode_iter1_gen] wrote {written} trajectories "
                              f"(task {i + 1}/{len(tasks)})", flush=True)
                except Exception as exc:
                    print(f"[intercode_iter1_gen] task {i} failed: {exc}", flush=True)
                    continue
    except Exception as exc:
        print(f"[intercode_iter1_gen] gen loop aborted: {exc}", flush=True)

    print(f"[intercode_iter1_gen] generated {written}/{len(tasks)} iter1 trajectories.", flush=True)
    return written


def filter_iter1_trajectories(
    raw_path: "str | Path",
    output_path: "str | Path",
    *,
    threshold: float = DEFAULT_REWARD_THRESHOLD,
) -> "tuple[int, int]":
    """Rejection-sample: keep trajectories with reward >= threshold.

    Reads JSONL {"messages", "reward"} from raw_path; writes a DatasetDict with
    {"messages": ...} rows (the tokenize chain's input shape) to output_path.
    Returns (kept, total). Never raises.
    """
    kept_rows: list[dict] = []
    total = 0
    try:
        with open(raw_path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                total += 1
                try:
                    row = json.loads(line)
                except Exception:
                    continue
                if float(row.get("reward", 0.0)) >= threshold and row.get("messages"):
                    kept_rows.append({"messages": row["messages"]})
    except FileNotFoundError:
        print(f"[intercode_iter1_gen] raw path missing: {raw_path}", flush=True)
        return 0, 0
    except Exception as exc:
        print(f"[intercode_iter1_gen] filter read failed: {exc}", flush=True)
        return 0, total

    if not kept_rows:
        print(f"[intercode_iter1_gen] filter kept 0/{total}; nothing to save.", flush=True)
        return 0, total

    try:
        from datasets import Dataset, DatasetDict
        ds = Dataset.from_list(kept_rows)
        if len(kept_rows) > 1:
            frac = min(0.1, max(1.0 / len(kept_rows), 0.01))
            split = ds.train_test_split(test_size=frac, seed=0)
            dd = DatasetDict({"train": split["train"], "validation": split["test"]})
        else:
            dd = DatasetDict({"train": ds, "validation": ds})
        dd.save_to_disk(str(output_path))
    except Exception as exc:
        print(f"[intercode_iter1_gen] filter save failed: {exc}", flush=True)
        return 0, total

    print(f"[intercode_iter1_gen] filter kept {len(kept_rows)}/{total} (reward>={threshold}).", flush=True)
    return len(kept_rows), total


def run_iter1_phase(
    iter0_model_path: "str | Path",
    task_dataset_path: "str | Path",
    snapshot_root: "str | Path",
    iter1_output_path: "str | Path",
    *,
    keep_iter0_fraction: float = DEFAULT_KEEP_ITER0_FRACTION,
    max_tasks: "int | None" = DEFAULT_MAX_TASKS,
    max_turns: int = 10,
    temperature: float = 0.7,
) -> bool:
    """Top-level: generate -> filter -> stash iter1 data at iter1_output_path.

    Returns True when usable iter1 data was written, else False (caller falls back
    to a single-pass SFT). `keep_iter0_fraction` is advisory for the caller when it
    mixes the original gold back in. Never raises.
    """
    if not iter_sft_enabled():
        print("[intercode_iter1_gen] INTERCODE_ITER_SFT=0; skipping iter1.", flush=True)
        return False
    try:
        raw_path = str(Path(iter1_output_path).with_suffix(".raw.jsonl"))
        n = generate_iter1_trajectories(
            iter0_model_path, task_dataset_path, snapshot_root, raw_path,
            max_tasks=max_tasks, max_turns=max_turns, temperature=temperature,
        )
        if n == 0:
            print("[intercode_iter1_gen] no iter1 trajectories; falling back to single-pass.", flush=True)
            return False
        kept, total = filter_iter1_trajectories(raw_path, iter1_output_path)
        if kept == 0:
            print("[intercode_iter1_gen] all iter1 trajectories filtered out; falling back.", flush=True)
            return False
        print(f"[intercode_iter1_gen] iter1 ready: {kept}/{total} trajectories at {iter1_output_path} "
              f"(mix ~{keep_iter0_fraction:.0%} iter0 gold downstream for stability).", flush=True)
        return True
    except Exception as exc:
        print(f"[intercode_iter1_gen] run_iter1_phase failed: {exc}; falling back.", flush=True)
        return False


__all__ = [
    "DEFAULT_REWARD_THRESHOLD",
    "DEFAULT_KEEP_ITER0_FRACTION",
    "DEFAULT_MAX_TASKS",
    "iter_sft_enabled",
    "generate_iter1_trajectories",
    "filter_iter1_trajectories",
    "run_iter1_phase",
]
